PruebaEmpresa/Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PruebaEmpresa.Infraestructura;
using PruebaEmpresa.Contexto.Interfaces;
using PruebaEmpresa.Models;
using Stripe;
using Stripe.Checkout;
using PruebaEmpresa.Util;
using PruebaEmpresa.Contexto;
using System.Data.Entity;

namespace PruebaEmpresa.Controllers
{
    [SessionExpireAttribute]
    [Authorize]
    public class PagoController : Controller
    {
        ICargos_Repo Cargos_Repo;
        IUsuarios_Repo Usuarios_Repo;
        IRegistroPagos_Repo RegistroPagos_Repo;
        IProveedores_Repo Proveedores_Repo;
        ICancelarSuscripcion_Repo CancelarSuscripcion_Repo;

        public PagoController(ICargos_Repo cargos_Repo, IUsuarios_Repo usuarios_Repo, IRegistroPagos_Repo registroPagos_Repo,
            IProveedores_Repo proveedores_Repo, ICancelarSuscripcion_Repo cancelarSuscripcion_Repo)
        {
            Cargos_Repo = cargos_Repo;
            Usuarios_Repo = usuarios_Repo;
            RegistroPagos_Repo = registroPagos_Repo;
            Proveedores_Repo = proveedores_Repo;
            CancelarSuscripcion_Repo = cancelarSuscripcion_Repo;
        }



        public ActionResult Eliminar_Suscripcion(int? Cargo_ID)
        {
            int Usuario_ID = Cls_Sesiones.USUARIO_ID;
            CargosView cargosView = new CargosView();

            try
            {
                if (Cargo_ID.HasValue)
                {
                    cargosView = Cargos_Repo.Obtener_Un_Cargo(Cargo_ID.Value);
                }
                

            }
            catch (Exception ex) {

            }

            return View(cargosView);
        }


        [HttpPost]
        public ActionResult Eliminar_Suscripcion(int Cargo_ID)
        {
            CargosView cargosView = new CargosView();
            bool blnPagoExito = false; 

            try
            {
                UsuariosView usuariosView = Usuarios_Repo.Obtener_Usuario(Cls_Sesiones.USUARIO_ID);
                cargosView = Cargos_Repo.Obtener_Un_Cargo(Cargo_ID);

                StripeConfiguration.ApiKey = ConfigurationManager.AppSettings["stripeSecretkey"];
                var service = new SubscriptionService();
                service.Cancel(usuariosView.SubscriptionID);

                using (EFDbContext context = new EFDbContext())
                {
                    using (DbContextTransaction transaction = context.Database.BeginTransaction())
                    {

                        try
                        {

                            CancelarSuscripcionView cancelarSuscripcion = new CancelarSuscripcionView();
                            cancelarSuscripcion.Cargo_ID = cargosView.Cargo_ID;
                            cancelarSuscripcion.Identificador = usuariosView.SubscriptionID;
                            cancelarSuscripcion.Usuarios_ID = usuariosView.Usuarios_ID;

                            CancelarSuscripcion_Repo.Registrar_Cancelacion(context, cancelarSuscripcion);
                            Usuarios_Repo.Eliminar_SucriptionID(context, usuariosView.Usuarios_ID);

                            transaction.Commit();
                            blnPagoExito = true;
                        }
                        catch (Exception ex)
                        {
                         
                            transaction.Rollback();
                            ModelState.AddModelError("error", ex.Message);
                        }

                    }
                }



            }
            catch (Exception ex)
            {
                ModelState.AddModelError("error", ex.Message);
            }

            if (blnPagoExito) {
                return RedirectToAction("Listado_Cargos");
            }


            return View(cargosView);
        }


        public ActionResult Listado_Cargos()
        {
            CargosSeleccionView cargosSeleccionView = new CargosSeleccionView();

            try {

                StripeConfiguration.ApiKey = ConfigurationManager.AppSettings["stripeSecretkey"];

                UsuariosView usuariosView = Usuarios_Repo.Obtener_Usuario(Cls_Sesiones.USUARIO_ID);

                if (usuariosView.SubscriptionID.Trim().Length > 0)
                {
                    var service = new SubscriptionService();
                    Subscription subscription = service.Get(usuariosView.SubscriptionID);

                    if(subscription.Status == "active")
                    {
                        cargosSeleccionView.Tiene_Pago = true;

                        RegistroPagosView registroPagosView = RegistroPagos_Repo.Obtener_Registro_Pago_Actual(Cls_Sesiones.USUARIO_ID);
                         if(registroPagosView != null)
                         {
                              
                               cargosSeleccionView.Cargo_ID = registroPagosView.Cargo_ID;
                          }


                    }
                }

                List<CargosView> Lista_Cargos_View = Cargos_Repo.Obtener_Cargos_Activos();
                cargosSeleccionView.Lista_Cargo = Lista_Cargos_View;

                if(Proveedores_Repo.Obtener_Proveedores(Cls_Sesiones.USUARIO_ID).Count() > 0)
                {
                    cargosSeleccionView.Tiene_Proveedor = true;
                }


            }
            catch(Exception ex)
            {

            }
           

            return View(cargosSeleccionView);
        }


        public ActionResult Hacer_Pago(int? Cargo_ID)
        {
            int Usuario_ID = Cls_Sesiones.USUARIO_ID;
            CargosView cargosView = new CargosView();
            Cls_Cargo_Pago cls_Cargo_Pago = new Cls_Cargo_Pago();
            CheckOutView checkOutView = new CheckOutView();
            try
            {
                ViewBag.StripePublishKey = ConfigurationManager.AppSettings["stripePublishableKey"];

                UsuariosView usuariosView = Usuarios_Repo.Obtener_Usuario(Usuario_ID);

                if(usuariosView != null)
                {
                    cls_Cargo_Pago.Email = usuariosView.Correo_Electronico;
                    cls_Cargo_Pago.Phone = usuariosView.Telefono;
                }

                if (Cargo_ID.HasValue)
                {
                    cargosView = Cargos_Repo.Obtener_Un_Cargo(Cargo_ID.Value);
                    cls_Cargo_Pago.Cargo_ID = Cargo_ID.Value;
                }
                else
                {
                    cls_Cargo_Pago.Cargo_ID = 0;
                }

                checkOutView.cargosView = cargosView;
                checkOutView.cls_Cargo_Pago = cls_Cargo_Pago;


            }catch(Exception ex)
            {

            }

            return View(checkOutView);
        }


        public ActionResult Success( int Cargo_ID)
        {
            CargosView cargosView;

            cargosView = Cargos_Repo.Obtener_Un_Cargo(Cargo_ID);

            return View(cargosView);
        }

        public ActionResult Exitoso()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Crear(CheckOutView checkOutView)
        {
            CargosView cargosView = new CargosView();
            checkOutView.Mensaje = "";
            UsuariosView usuariosView;
            bool blnPagoExito = false;
            string customerID = "";
            try
            {
                ViewBag.StripePublishKey = ConfigurationManager.AppSettings["stripePublishableKey"];
                cargosView = Cargos_Repo.Obtener_Un_Cargo(checkOutView.cls_Cargo_Pago.Cargo_ID);

                if (ModelState.IsValid)
                {
                    
                    StripeConfiguration.ApiKey = ConfigurationManager.AppSettings["stripeSecretkey"];

                    // verificamos si el correo de usuario esta agregado como cliente en la plataforma

                    usuariosView = Usuarios_Repo.Obtener_Usuario(Cls_Sesiones.USUARIO_ID);

                    if(usuariosView.CustomerID.Trim().Length == 0)
                    {

                        // creamos un cliente
                        var customerOptions = new CustomerCreateOptions
                        {
                            Description = checkOutView.cls_Cargo_Pago.CardName,
                            Source = checkOutView.cls_Cargo_Pago.stripeToken,
                            Email = checkOutView.cls_Cargo_Pago.Email,
                            Metadata = new Dictionary<string, string>()
                        {
                            {"Teléfono", checkOutView.cls_Cargo_Pago.Phone }
                        }
                        };

                        // se hace un registro del cliente en la plataforma de stripe
                        var customerService = new CustomerService();
                        Customer customer = customerService.Create(customerOptions);

                        // ese id se le agregamos a la basde de datos
                        customerID = customer.Id;
                        Usuarios_Repo.Agregar_Customer_ID(Cls_Sesiones.USUARIO_ID, customerID);
                    }
                    else
                    {
                        customerID = usuariosView.CustomerID;
                    }


                    // haremos la suscprición 


                    var optionsSubcription = new SubscriptionCreateOptions
                    {
                        Customer = customerID,
                        Items = new List<SubscriptionItemOptions>
                          {
                            new SubscriptionItemOptions
                            {
                              Price = cargosView.ProductoFinancieroID,
                            },
                          },
                    };


                    var service = new SubscriptionService();
                    Subscription subscription =  service.Create(optionsSubcription);

PruebaEmpresa/Views/Pago/Eliminar_Suscripcion.cshtml
@model PruebaEmpresa.Models.CargosView

@{
    ViewBag.Title = "Eliminar Suscripcion";
    Layout = "~/Views/Shared/_LayoutPageProveedor.cshtml";
}


@section scripts{


    <script type="text/javascript">

        $(function () {
            $('#btnSubmit').click(function () {
                var ventantaEspera = $('#Ventana_Espera');
                ventantaEspera.modal();
            });

        });

    </script>

}

<div class="page-header">
    <h3>Cancelar Suscripci&oacute;n </h3>
</div>



<div class="panel panel-primary">

    <div class="panel-heading clearfix">
        <h4 class="panel-title pull-left" style="padding-top: 7.5px;"> ¿Esta seguro de eliminar esta suscripci&oacute;n?</h4>
        <div class="btn-group pull-right">
            <a class="btn btn-success btn-sm" href="@Url.Action("Listado_Cargos","Pago")">Regresar <span class="glyphicon glyphicon-share-alt"></span> </a>
        </div>
    </div>

    <div class="panel-body">

        <div>

            @if (ViewData.ModelState.Any(x => x.Value.Errors.Any()))
            {

                <div class="alert alert-danger alert-dismissable" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    @Html.ValidationSummary()

                </div>

            }

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nombre_Cargo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nombre_Cargo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Precio)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Precio)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Dias)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Dias)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" id="btnSubmit" value="Cancelar" class="btn btn-danger" />

                </div>
            }

        </div>

    </div>

</div>





<div id="Ventana_Espera" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Procesando</h4>
            </div>
            <div class="modal-body">
                <div class="progress">
                    <div class="progress-bar progress-bar-striped active" role="progressbar"
                         aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">

                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

PruebaEmpresa/Views/Pago/Exitoso.cshtml
@{
    ViewBag.Title = "Exitoso";
    Layout = "~/Views/Shared/_LayoutPageProveedor.cshtml";
}

<h2>Exitoso</h2>

PruebaEmpresa/Views/Pago/Hacer_Pago.cshtml
@model PruebaEmpresa.Models.CheckOutView

@{
    ViewBag.Title = "Hacer_Pago";
    Layout = "~/Views/Shared/_LayoutPageProveedor.cshtml";
}

<style media="screen">

    .green {
        border: solid green 1px;
    }

    .error {
        border: solid red 1px;
    }
</style>

@section scripts{

    <script type="text/javascript">
        function preventBack() { window.history.forward(); }
        setTimeout("preventBack()", 0);
        window.onunload = function () { null };
    </script>


    <script src="https://js.stripe.com/v3/" type="text/javascript"></script>

    <script type="text/javascript">

        var ObjFormPagoViewModel;

        $(function () {

            ObjFormPagoViewModel = new FormPagoViewModel();
            ObjFormPagoViewModel.ModelFormPago.errors = ko.validation.group(ObjFormPagoViewModel.ModelFormPago);
            ko.applyBindings(ObjFormPagoViewModel, $("#interfaz_pago")[0]);

            var mensaje = '@Model.Mensaje';

            if (mensaje.length > 0) {

                $.toast({
                    heading: 'Centro Capacitación',
                    text: mensaje,
                    position: 'top-right',
                    stack: false

                });
            }

        });

        var stripe = Stripe('@ViewBag.StripePublishKey');
        // Create an instance of Elements.
        var elements = stripe.elements();

        // Create an instance of the card Element.
        //var card = elements.create('card', { style: style });
        var card = elements.create('cardNumber', {
            classes: {
                base: "form-control",
                invalid: "error"
            }

        });

        var cvc = elements.create('cardCvc', {
            classes: {
                base: "form-control",
                invalid: "error"
            }

        });


        var exp = elements.create('cardExpiry', {
            classes: {
                base: "form-control",
                invalid: "error"
            }

        });

        // Add an instance of the card Element into the `card-element` <div>.
        card.mount('#card-element');
        cvc.mount('#card-cvc');
        exp.mount('#card-exp');

        // Handle real-time validation errors from the card Element.
        card.addEventListener('change', function (event) {
            var displayError = document.getElementById('card-errors');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });

        // Handle form submission.
        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function (event) {
            event.preventDefault();

            stripe.createToken(card).then(function (result) {
                if (result.error) {
                    // Inform the user if there was an error.
                    var errorElement = document.getElementById('card-errors');
                    errorElement.textContent = result.error.message;
                } else {
                    // Send the token to your server.
                    stripeTokenHandler(result.token);
                }
            });
        });

        // Submit the form with the token ID.
        function stripeTokenHandler(token) {
            // Insert the token ID into the form so it gets submitted to the server
            var form = document.getElementById('payment-form');
            //var hiddenInput = document.createElement('input');
            //hiddenInput.setAttribute('type', 'hidden');
            //hiddenInput.setAttribute('name', 'stripeToken');
            //hiddenInput.setAttribute('value', token.id);
            //form.appendChild(hiddenInput);

            var token_control = document.getElementById('cls_Cargo_Pago_stripeToken');
            token_control.value = token.id;


            if (ObjFormPagoViewModel.ModelFormPago.errors().length == 0) {
                var ventantaEspera = $('#Ventana_Espera');
                ventantaEspera.modal();
                //Submit the form
                form.submit();
            } else {
                ObjFormPagoViewModel.ModelFormPago.errors.showAllMessages();
            }

        }

        var FormPagoModel = function () {

            var _NombreTarjeta = ko.observable('').extend({ required: true })
                      .extend({ maxLength: 100 })
                      .extend({ caracterPermitido: 'ÁÉÍÓÚáéíóúñÑ_/-().' }),
                _Telefono = ko.observable('@Model.cls_Cargo_Pago.Phone').extend({ required: true })
                     .extend({ digit: true })
                     .extend({ minLength: 10 })
                     .extend({ maxLength: 10 }),
                _CorreoElectronico = ko.observable('@Model.cls_Cargo_Pago.Email')
                     .extend({ required: true })
                     .extend({ email: true })
                     .extend({ maxLength: 50 });

            return {
                NombreTarjeta: _NombreTarjeta,
                Telefono: _Telefono,
                CorreoElectronico: _CorreoElectronico
            }
        }



        function FormPagoViewModel() {
            var self = this;
            ko.validation.locale('es-ES');
            "use strict";

            self.ModelFormPago = FormPagoModel();

        }

    </script>


}



<div class="row">


    <div class="col-md-6 col-sm-offset-3">


        <div class="panel panel-success">

            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left">Datos Financieros</h4>

                <div class="btn-group pull-right">
                    <a class="btn btn-success btn-sm" href="@Url.Action("Listado_Cargos","Pago")">Regresar <span class="glyphicon glyphicon-share-alt"></span></a>
                </div>

            </div>

            <div class="panel-body">


                <form action="/Pago/Crear" method="post" id="payment-form">

                    @Html.HiddenFor(x => x.cls_Cargo_Pago.stripeToken)
                    @Html.HiddenFor(x => x.cls_Cargo_Pago.Cargo_ID)


                    <div id="interfaz_pago">

                        <div class="form-group">
                            <label for="card-name">*Nombre en la tarjeta</label>
                            @Html.TextBoxFor(model => model.cls_Cargo_Pago.CardName, new { @class = "form-control" ,data_bind= "textInput: ModelFormPago.NombreTarjeta" })
                            @Html.ValidationMessageFor(model => model.cls_Cargo_Pago.CardName, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label for="card-name">*Correo Electr&oacute;nico</label>
                            @Html.TextBoxFor(model => model.cls_Cargo_Pago.Email, new { @class = "form-control", data_bind = "textInput: ModelFormPago.CorreoElectronico", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.cls_Cargo_Pago.Email, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label for="card-name">*Tel&eacute;fono</label>
                            @Html.TextBoxFor(model => model.cls_Cargo_Pago.Phone, new { @class = "form-control", data_bind = "textInput: ModelFormPago.Telefono", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.cls_Cargo_Pago.Phone, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label for="card-element">
                                *Tarjeta de Cr&eacute;dito o D&eacute;bito
                            </label>
                            <div id="card-element">
                                <!-- A Stripe Element will be inserted here. -->
                            </div>
                        </div>


                        <div class="form-group">

                            <div class="row">

                                <div class="col-md-6">

                                    <div class="form-group">
                                        <label for="card-cvc">
                                            *cvc
                                        </label>
                                        <div id="card-cvc">
                                            <!-- A Stripe Element will be inserted here. -->
                                        </div>
                                    </div>

                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="card-exp">
                                            *exp
                                        </label>
                                        <div id="card-exp">
                                            <!-- A Stripe Element will be inserted here. -->
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>


                        <!-- Used to display Element errors. -->
                        <div id="card-errors" role="alert"></div>

                        <div class="form-group">
                            <button class="form-control btn btn-primary">Realizar Pago</button>
                        </div>


                    </div>
                </form>


            </div>

        </div>

    </div>

</div>


<div class="row">


    <div class="col-md-6 col-sm-offset-3">

        <div class="panel panel-primary">

            <div class="panel-heading">
                <h4 class="panel-title">Cargos</h4>
            </div>

            <div class="panel-body">

                <dl class="dl-horizontal">

                    <dt>
                        @Html.DisplayNameFor(model => model.cargosView.Nombre_Cargo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.cargosView.Nombre_Cargo)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.cargosView.Dias)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.cargosView.Dias)
                    </dd>


                    <dt>
                        @Html.DisplayNameFor(model => model.cargosView.Precio)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.cargosView.Precio)
                    </dd>




                </dl>

            </div>


        </div>

    </div>

</div>


<div id="Ventana_Espera" class="modal fade" data-backdrop="static" data-keyboard="false" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Procesando</h4>
            </div>
            <div class="modal-body">
                <div class="progress">
                    <div class="progress-bar progress-bar-striped active" role="progressbar"
                         aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">

                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

PruebaEmpresa/Views/Pago/Iniciar_Suscripcion.cshtml
@{
    ViewBag.Title = "Iniciar_Suscripcion";
    Layout = "~/Views/Shared/_LayoutPageProveedor.cshtml";
}


@section scripts{

    <script src="https://js.stripe.com/v3/" type="text/javascript"></script>

    <script type="text/javascript">
        var stripe = Stripe('@ViewBag.StripePublishKey');


        document
        .getElementById("checkout")
         .addEventListener("click", function (evt) {
      // You'll have to define PRICE_ID as a price ID before this code block
      createCheckoutSession('price_1J4rBpLJvtqh8HFDspMcr75b').then(function (data) {
          // Call Stripe.js method to redirect to the new Checkout page
          stripe
            .redirectToCheckout({
                sessionId: data.sessionId
            })
            .then(handleResult);
        });
      });


        var createCheckoutSession = function (priceId) {
            return fetch("../Pago/Crear_Session", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    priceId: priceId
                })
            }).then(function (result) {
                return result.json();
            });
        };



    </script>

    }

    <h2>Iniciar_Suscripcion</h2>


    <button id="checkout">Subscribe</button>

PruebaEmpresa/Views/Pago/Listado_Cargos.cshtml
@model PruebaEmpresa.Models.CargosSeleccionView

@{
    ViewBag.Title = "Listado de Cargos";
    Layout = "~/Views/Shared/_LayoutPageProveedor.cshtml";
}

<div class="page-header ">
    <h3>Cargos Disponibles</h3>
</div>


@if(Model.Tiene_Proveedor == false)
{

    <span class="label label-danger">Se requiere dar alta un proveedor</span>
    <br />
    <br />

}

@foreach(var item in Model.Lista_Cargo)
{


    <div class="panel panel-primary">

        <div class="panel-heading">
            <h4 class="panel-title"> @item.Nombre_Cargo </h4>
        </div>
        <div class="panel-body">

             <div class="row">

                 <div class="col-md-6">
                     <b> N&uacute;mero de d&iacute;as disponible :  </b>    <span class="badge">@item.Dias</span>
                 </div>

                 <div class="col-md-6">


                     @if (Model.Tiene_Proveedor == true && Model.Tiene_Pago == false)
                     {
                         <div style="text-align:right">
                             <a href="@Url.Action("Hacer_Pago", "Pago", new { Cargo_ID = item.Cargo_ID })" class="btn btn-primary custom">  Pagar <span> @item.Precio $</span> </a>
                         </div>
                     }
                     else
                     {
                         <div style="text-align:right">
                             <a href="#" class="btn btn-primary custom disabled">  Pagar <span> @item.Precio $</span> </a>
                         </div>
                     }


                 </div>

             </div>

             <div>
                 @if (Model.Cargo_ID == item.Cargo_ID)
                 {
                     <span class="label label-danger">Este cargo ha sido adquirido</span>
                 }
             </div>

        </div>

        @if (Model.Tiene_Pago && Model.Cargo_ID == item.Cargo_ID)
        {
            <div class="panel-footer clearfix">

                 <div class="btn-group pull-right">
                      
                      <a href="@Url.Action("Eliminar_Suscripcion","Pago", new { Cargo_ID = item.Cargo_ID } )" class="btn btn-danger btn-sm" > Cancelar  </a>

                 </div>

            </div>
        }

    </div>
}

PruebaEmpresa/Views/Pago/Success.cshtml
@model PruebaEmpresa.Models.CargosView

@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_LayoutPageProveedor.cshtml";
}


@section scripts{



}


<div class="page-header ">
    <h3>Pago Exitoso</h3>
</div>


<div class="panel panel-primary">

    <div class="panel-heading clearfix">
        <h4 class="panel-title pull-left" style="padding-top: 7.5px;"> Usted adquiri&oacute; el siguiente cargo </h4>
    </div>

    <div class="panel panel-body">

        <div>

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nombre_Cargo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nombre_Cargo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Precio)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Precio)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Dias)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Dias)
                </dd>

            </dl>

        </div>

    </div>

</div>